// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwggOf-KCrYyVoTRdqIwkiAmaxgrOBRc',
    appId: '1:778030115762:web:9ff96f1aee8138c37ed2ab',
    messagingSenderId: '778030115762',
    projectId: 'smartcoach-ce3e4',
    authDomain: 'smartcoach-ce3e4.firebaseapp.com',
    storageBucket: 'smartcoach-ce3e4.firebasestorage.app',
    measurementId: 'G-MW35NETT2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ48YEwwU1-ZSlcAhM2UX_2oK-EaZkVec',
    appId: '1:778030115762:android:f6557d2afb4765707ed2ab',
    messagingSenderId: '778030115762',
    projectId: 'smartcoach-ce3e4',
    storageBucket: 'smartcoach-ce3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcsFe91nLBfDGRCxeq5RwfEygg9UP8z4',
    appId: '1:778030115762:ios:518b2400599c535c7ed2ab',
    messagingSenderId: '778030115762',
    projectId: 'smartcoach-ce3e4',
    storageBucket: 'smartcoach-ce3e4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApcsFe91nLBfDGRCxeq5RwfEygg9UP8z4',
    appId: '1:778030115762:ios:518b2400599c535c7ed2ab',
    messagingSenderId: '778030115762',
    projectId: 'smartcoach-ce3e4',
    storageBucket: 'smartcoach-ce3e4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKwggOf-KCrYyVoTRdqIwkiAmaxgrOBRc',
    appId: '1:778030115762:web:08e9850b7e8613707ed2ab',
    messagingSenderId: '778030115762',
    projectId: 'smartcoach-ce3e4',
    authDomain: 'smartcoach-ce3e4.firebaseapp.com',
    storageBucket: 'smartcoach-ce3e4.firebasestorage.app',
    measurementId: 'G-NSPJSQW89S',
  );
}
